/*
 * Generated by parse_shadertoy_json.py
 */

char* shadername = "molten bismuth";
int texdims[] = {
256, 256, 4,
256, 256, 3,
96, 96, 3,
0, 0, 0,
256, 256, 4,
512, 512, 3,
96, 96, 3,
96, 96, 3,
96, 96, 3,
0, 0, 0,
0, 0, 0,
0, 0, 0,
0, 0, 0,
0, 0, 0,
0, 0, 0,
0, 0, 0,
};
